version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka-broker:
    image: confluentinc/cp-kafka:6.1.1
    hostname: broker
    container_name: broker
    depends_on:
    - zookeeper
    ports:
    - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  publisher:
    container_name: publisher
    hostname: publisher
    build: ./publisher/
    environment:
      - BROKER_IP=broker
      - BROKER_PORT=9092
      - TOPIC=statistics
    command: "python ./publisher.py"
    

  database:
    container_name: database_sql
    hostname: database_sql
    build: ./db/
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    
            
  subscriber:
    build: ./subscriber/
    container_name: subscriber
    hostname: subscriber
    environment:
      - TOPIC=statistics
      - BROKER_IP=broker
      - BROKER_PORT=9092
      - DB_LOGIN=clientstat
      - DB_PWD=123456
      - DB_IP=database_sql
      - DB_PORT=3306
    command: "python ./subscriber.py"